#!/bin/bash

deepspeed llava/train/train_veritas.py \
    --deepspeed ./scripts/zero3.json \
    --model_name_or_path /home/zehong/LLaVA/checkpoints/llava-v1.5-13b-pretrain-1211k-finetune-665k \
    --version v1 \
    --data_path ./data/instruction/finetune_198253_cmm_70k_vm_100k_tm_13k_mix_15k.json \
    --image_folder ./data \
    --vision_tower openai/clip-vit-large-patch14-336 \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --mm_vision_tower_lr 2e-6 \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir ./checkpoints/veritas-13b-pretrain_1211k-finetune_665k-newstune_198k \
    --num_train_epochs 3 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 2 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 10000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 4096 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb